export interface RecommendationCatalogItem {
  rec_id: string;
  skill_id: string;
  item_type: ItemType;
  title: string;
  description: string;
  url: string | null;
  difficulty: Difficulty;
  estimated_hours: number;
  is_active: boolean;
}

export type ItemType = "course" | "project" | "certification" | "internship";
export type Difficulty = "beginner" | "intermediate" | "advanced";

// ---------------------------------------------------------------------------
// Recommendation Catalog (61 records)
// ---------------------------------------------------------------------------

export const recommendationCatalog: RecommendationCatalogItem[] = [
  {
    rec_id: "RC001",
    skill_id: "SK001",
    item_type: "course",
    title: "Python for Everybody (Coursera)",
    description:
      "Beginner Python course by University of Michigan. Covers basics through data structures.",
    url: "https://www.coursera.org/specializations/python",
    difficulty: "beginner",
    estimated_hours: 60,
    is_active: true,
  },
  {
    rec_id: "RC002",
    skill_id: "SK001",
    item_type: "course",
    title: "Automate the Boring Stuff with Python",
    description:
      "Free online book and course teaching practical Python automation.",
    url: "https://automatetheboringstuff.com",
    difficulty: "beginner",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC003",
    skill_id: "SK001",
    item_type: "project",
    title: "Build a Web Scraper in Python",
    description:
      "Use requests and BeautifulSoup to scrape and store data from a public website.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 8,
    is_active: true,
  },
  {
    rec_id: "RC004",
    skill_id: "SK001",
    item_type: "certification",
    title: "PCEP – Python Certified Entry-Level Programmer",
    description: "Entry-level Python certification from Python Institute.",
    url: "https://pythoninstitute.org/pcep",
    difficulty: "beginner",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC005",
    skill_id: "SK003",
    item_type: "course",
    title: "The Odin Project – Full Stack JavaScript",
    description:
      "Free open-source curriculum covering JavaScript from foundations to full stack.",
    url: "https://www.theodinproject.com",
    difficulty: "beginner",
    estimated_hours: 120,
    is_active: true,
  },
  {
    rec_id: "RC006",
    skill_id: "SK003",
    item_type: "course",
    title: "JavaScript.info",
    description: "Free comprehensive modern JavaScript tutorial.",
    url: "https://javascript.info",
    difficulty: "beginner",
    estimated_hours: 50,
    is_active: true,
  },
  {
    rec_id: "RC007",
    skill_id: "SK003",
    item_type: "project",
    title: "Build a To-Do App with Vanilla JS",
    description:
      "Create a functional to-do list app without any framework using DOM manipulation.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 6,
    is_active: true,
  },
  {
    rec_id: "RC008",
    skill_id: "SK004",
    item_type: "course",
    title: "TypeScript Handbook (Official Docs)",
    description: "Free official TypeScript documentation and learning guide.",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    difficulty: "intermediate",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC009",
    skill_id: "SK004",
    item_type: "project",
    title: "Refactor a JS Project to TypeScript",
    description:
      "Take an existing JavaScript project and migrate it to TypeScript with strict mode.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC010",
    skill_id: "SK019",
    item_type: "course",
    title: "React Official Tutorial",
    description: "Free interactive tutorial from the React team.",
    url: "https://react.dev/learn",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC011",
    skill_id: "SK019",
    item_type: "project",
    title: "Build a Weather App with React",
    description:
      "Create a weather dashboard using a free public API and React state management.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 12,
    is_active: true,
  },
  {
    rec_id: "RC012",
    skill_id: "SK019",
    item_type: "project",
    title: "Build a Blog CMS Frontend with React",
    description:
      "Implement a content management interface with CRUD functionality.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC013",
    skill_id: "SK016",
    item_type: "course",
    title: "SQLZoo",
    description: "Free interactive SQL tutorial with exercises for all levels.",
    url: "https://sqlzoo.net",
    difficulty: "beginner",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC014",
    skill_id: "SK016",
    item_type: "course",
    title: "Mode Analytics SQL Tutorial",
    description:
      "Free structured SQL learning path covering beginner to advanced.",
    url: "https://mode.com/sql-tutorial",
    difficulty: "beginner",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC015",
    skill_id: "SK016",
    item_type: "project",
    title: "Analyze a Public Dataset with SQL",
    description:
      "Use a public dataset (e.g., COVID PH data) to write queries and produce insights.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 8,
    is_active: true,
  },
  {
    rec_id: "RC016",
    skill_id: "SK016",
    item_type: "certification",
    title: "Oracle Database SQL Certified Associate",
    description: "Vendor certification for SQL fundamentals.",
    url: "https://education.oracle.com",
    difficulty: "intermediate",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC017",
    skill_id: "SK040",
    item_type: "course",
    title: "PostgreSQL Tutorial (postgresqltutorial.com)",
    description:
      "Free comprehensive guide to PostgreSQL from basics to advanced.",
    url: "https://www.postgresqltutorial.com",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC018",
    skill_id: "SK040",
    item_type: "project",
    title: "Design a Database Schema from Scratch",
    description:
      "Model a real-world scenario (e.g., university enrollment) and implement it in PostgreSQL.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC019",
    skill_id: "SK075",
    item_type: "course",
    title: "Docker's Official Get Started Guide",
    description: "Free official tutorial for learning Docker fundamentals.",
    url: "https://docs.docker.com/get-started/",
    difficulty: "intermediate",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC020",
    skill_id: "SK075",
    item_type: "project",
    title: "Containerize a Web Application",
    description:
      "Package an existing Node or Python app into a Docker container and run it locally.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 8,
    is_active: true,
  },
  {
    rec_id: "RC021",
    skill_id: "SK075",
    item_type: "certification",
    title: "Docker Certified Associate (DCA)",
    description:
      "Official Docker certification for container management skills.",
    url: "https://training.mirantis.com/certification/dca-certification-exam/",
    difficulty: "advanced",
    estimated_hours: 60,
    is_active: true,
  },
  {
    rec_id: "RC022",
    skill_id: "SK111",
    item_type: "course",
    title: "Git and GitHub Crash Course (freeCodeCamp)",
    description:
      "Free YouTube tutorial covering Git basics and GitHub workflows.",
    url: "https://www.youtube.com/watch?v=RGOj5yH7evk",
    difficulty: "beginner",
    estimated_hours: 6,
    is_active: true,
  },
  {
    rec_id: "RC023",
    skill_id: "SK111",
    item_type: "course",
    title: "Learn Git Branching (interactive)",
    description:
      "Free browser-based interactive tool for learning Git branching.",
    url: "https://learngitbranching.js.org",
    difficulty: "beginner",
    estimated_hours: 4,
    is_active: true,
  },
  {
    rec_id: "RC024",
    skill_id: "SK111",
    item_type: "project",
    title: "Contribute to an Open Source Project",
    description:
      "Find a beginner-friendly open source project on GitHub and submit a pull request.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC025",
    skill_id: "SK052",
    item_type: "course",
    title: "Machine Learning Specialization (Coursera – Andrew Ng)",
    description:
      "Foundational ML course covering regression, classification, and neural networks.",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    difficulty: "intermediate",
    estimated_hours: 90,
    is_active: true,
  },
  {
    rec_id: "RC026",
    skill_id: "SK052",
    item_type: "project",
    title: "Train a Classification Model on a Public Dataset",
    description:
      "Use scikit-learn to train and evaluate a classification model on a Kaggle dataset.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC027",
    skill_id: "SK052",
    item_type: "certification",
    title: "Google Professional Machine Learning Engineer",
    description:
      "Professional-level Google Cloud certification for ML practitioners.",
    url: "https://cloud.google.com/certification/machine-learning-engineer",
    difficulty: "advanced",
    estimated_hours: 120,
    is_active: true,
  },
  {
    rec_id: "RC028",
    skill_id: "SK051",
    item_type: "course",
    title: "Data Analysis with Python (freeCodeCamp)",
    description:
      "Free certification covering NumPy, Pandas, Matplotlib for data analysis.",
    url: "https://www.freecodecamp.org/learn/data-analysis-with-python/",
    difficulty: "beginner",
    estimated_hours: 30,
    is_active: true,
  },
  {
    rec_id: "RC029",
    skill_id: "SK051",
    item_type: "project",
    title: "Analyze a Philippine Public Dataset",
    description:
      "Download a PSA or DOLE dataset and produce a visual analysis report.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC030",
    skill_id: "SK072",
    item_type: "certification",
    title: "AWS Certified Cloud Practitioner",
    description: "Entry-level AWS certification covering cloud fundamentals.",
    url: "https://aws.amazon.com/certification/certified-cloud-practitioner/",
    difficulty: "beginner",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC031",
    skill_id: "SK072",
    item_type: "certification",
    title: "AWS Certified Solutions Architect – Associate",
    description: "Professional AWS certification for cloud architecture.",
    url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
    difficulty: "intermediate",
    estimated_hours: 80,
    is_active: true,
  },
  {
    rec_id: "RC032",
    skill_id: "SK073",
    item_type: "certification",
    title: "Google Associate Cloud Engineer",
    description:
      "GCP certification covering cloud infrastructure and services.",
    url: "https://cloud.google.com/certification/cloud-engineer",
    difficulty: "intermediate",
    estimated_hours: 80,
    is_active: true,
  },
  {
    rec_id: "RC033",
    skill_id: "SK074",
    item_type: "certification",
    title: "Microsoft Azure Fundamentals (AZ-900)",
    description: "Entry-level Azure certification for cloud concepts.",
    url: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/",
    difficulty: "beginner",
    estimated_hours: 30,
    is_active: true,
  },
  {
    rec_id: "RC034",
    skill_id: "SK084",
    item_type: "certification",
    title: "CompTIA Security+",
    description: "Widely recognized entry-level cybersecurity certification.",
    url: "https://www.comptia.org/certifications/security",
    difficulty: "intermediate",
    estimated_hours: 80,
    is_active: true,
  },
  {
    rec_id: "RC035",
    skill_id: "SK085",
    item_type: "certification",
    title: "CompTIA PenTest+",
    description: "Certification focused on penetration testing skills.",
    url: "https://www.comptia.org/certifications/pentest",
    difficulty: "advanced",
    estimated_hours: 100,
    is_active: true,
  },
  {
    rec_id: "RC036",
    skill_id: "SK085",
    item_type: "course",
    title: "TryHackMe – Pre-Security Path",
    description:
      "Free beginner-friendly cybersecurity learning platform with hands-on labs.",
    url: "https://tryhackme.com/path/outline/presecurity",
    difficulty: "beginner",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC037",
    skill_id: "SK087",
    item_type: "course",
    title: "OWASP WebGoat – Web Security Practice",
    description:
      "Free vulnerable app for practicing web application security concepts.",
    url: "https://owasp.org/www-project-webgoat/",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC038",
    skill_id: "SK094",
    item_type: "certification",
    title: "CompTIA Network+",
    description:
      "Vendor-neutral networking certification covering fundamentals.",
    url: "https://www.comptia.org/certifications/network",
    difficulty: "intermediate",
    estimated_hours: 80,
    is_active: true,
  },
  {
    rec_id: "RC039",
    skill_id: "SK094",
    item_type: "certification",
    title: "Cisco CCNA",
    description: "Industry-standard networking certification by Cisco.",
    url: "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html",
    difficulty: "intermediate",
    estimated_hours: 120,
    is_active: true,
  },
  {
    rec_id: "RC040",
    skill_id: "SK094",
    item_type: "course",
    title: "Networking Fundamentals (free – Cisco NetAcad)",
    description: "Free networking basics course from Cisco Networking Academy.",
    url: "https://www.netacad.com",
    difficulty: "beginner",
    estimated_hours: 30,
    is_active: true,
  },
  {
    rec_id: "RC041",
    skill_id: "SK131",
    item_type: "course",
    title: "Figma for Beginners (official Figma tutorial)",
    description: "Free interactive Figma tutorial on the Figma Community.",
    url: "https://www.figma.com/resources/learn-design/",
    difficulty: "beginner",
    estimated_hours: 8,
    is_active: true,
  },
  {
    rec_id: "RC042",
    skill_id: "SK128",
    item_type: "course",
    title: "Google UX Design Certificate (Coursera)",
    description:
      "Beginner-level UX design certificate covering the full design process.",
    url: "https://www.coursera.org/professional-certificates/google-ux-design",
    difficulty: "beginner",
    estimated_hours: 120,
    is_active: true,
  },
  {
    rec_id: "RC043",
    skill_id: "SK130",
    item_type: "project",
    title: "Design a Mobile App Prototype in Figma",
    description:
      "Pick a problem, sketch wireframes, and build a clickable high-fidelity prototype in Figma.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC044",
    skill_id: "SK115",
    item_type: "certification",
    title: "CompTIA A+",
    description:
      "Foundational IT support certification for hardware and software troubleshooting.",
    url: "https://www.comptia.org/certifications/a",
    difficulty: "beginner",
    estimated_hours: 80,
    is_active: true,
  },
  {
    rec_id: "RC045",
    skill_id: "SK118",
    item_type: "certification",
    title: "ITIL Foundation",
    description:
      "ITSM framework certification widely required in BPO and enterprise IT support.",
    url: "https://www.axelos.com/certifications/itil-service-management/itil-4-foundation",
    difficulty: "beginner",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC046",
    skill_id: "SK106",
    item_type: "course",
    title: "Testing JavaScript with Vitest (official docs)",
    description:
      "Free documentation and guide for writing unit and integration tests with Vitest.",
    url: "https://vitest.dev/guide/",
    difficulty: "intermediate",
    estimated_hours: 10,
    is_active: true,
  },
  {
    rec_id: "RC047",
    skill_id: "SK110",
    item_type: "course",
    title: "Scrum.org – Free Scrum Learning Path",
    description:
      "Free resources from Scrum.org for understanding Scrum framework.",
    url: "https://www.scrum.org/resources/learning-series/",
    difficulty: "beginner",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC048",
    skill_id: "SK110",
    item_type: "certification",
    title: "Professional Scrum Master I (PSM I)",
    description: "Entry-level Scrum Master certification from Scrum.org.",
    url: "https://www.scrum.org/assessments/professional-scrum-master-i-certification",
    difficulty: "beginner",
    estimated_hours: 30,
    is_active: true,
  },
  {
    rec_id: "RC049",
    skill_id: "SK105",
    item_type: "course",
    title: "System Design Primer (GitHub)",
    description:
      "Free comprehensive system design guide covering distributed systems concepts.",
    url: "https://github.com/donnemartin/system-design-primer",
    difficulty: "advanced",
    estimated_hours: 40,
    is_active: true,
  },
  {
    rec_id: "RC050",
    skill_id: "SK105",
    item_type: "project",
    title: "Design and Document a Scalable System Architecture",
    description:
      "Pick a real-world product and write an architecture document covering database, API, caching, and scaling decisions.",
    url: null,
    difficulty: "advanced",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC051",
    skill_id: "SK001",
    item_type: "internship",
    title: "Apply for a Python/Data Internship",
    description:
      "Search for IT or data internship opportunities at local PH companies or remote tech firms. Target roles that use Python.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 480,
    is_active: true,
  },
  {
    rec_id: "RC052",
    skill_id: "SK003",
    item_type: "internship",
    title: "Apply for a Web Development Internship",
    description:
      "Look for frontend or full-stack internship opportunities; portfolio required.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 480,
    is_active: true,
  },
  {
    rec_id: "RC053",
    skill_id: "SK051",
    item_type: "internship",
    title: "Apply for a Data Analyst Internship",
    description:
      "Seek data analyst internship roles in BPO, fintech, or e-commerce companies operating in the Philippines.",
    url: null,
    difficulty: "beginner",
    estimated_hours: 480,
    is_active: true,
  },
  {
    rec_id: "RC054",
    skill_id: "SK066",
    item_type: "course",
    title: "Microsoft Power BI Learning Path (free)",
    description:
      "Free official Microsoft learning path for Power BI fundamentals.",
    url: "https://learn.microsoft.com/en-us/training/powerplatform/power-bi",
    difficulty: "beginner",
    estimated_hours: 25,
    is_active: true,
  },
  {
    rec_id: "RC055",
    skill_id: "SK066",
    item_type: "certification",
    title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)",
    description: "Microsoft certification for Power BI data analysis skills.",
    url: "https://learn.microsoft.com/en-us/certifications/power-bi-data-analyst-associate/",
    difficulty: "intermediate",
    estimated_hours: 60,
    is_active: true,
  },
  {
    rec_id: "RC056",
    skill_id: "SK027",
    item_type: "course",
    title: "Laravel Official Documentation and Bootcamp",
    description: "Free official Laravel learning path and bootcamp tutorial.",
    url: "https://bootcamp.laravel.com",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC057",
    skill_id: "SK027",
    item_type: "project",
    title: "Build a CRUD Application with Laravel",
    description:
      "Create a full CRUD web app with authentication using Laravel and MySQL.",
    url: null,
    difficulty: "intermediate",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC058",
    skill_id: "SK100",
    item_type: "course",
    title: "Object-Oriented Programming in Java (Coursera – Duke)",
    description:
      "Free-to-audit OOP course using Java as the teaching language.",
    url: "https://www.coursera.org/learn/object-oriented-java",
    difficulty: "beginner",
    estimated_hours: 30,
    is_active: true,
  },
  {
    rec_id: "RC059",
    skill_id: "SK102",
    item_type: "course",
    title: "Refactoring Guru – Design Patterns",
    description:
      "Free website explaining all GoF design patterns with examples in multiple languages.",
    url: "https://refactoring.guru/design-patterns",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
  {
    rec_id: "RC060",
    skill_id: "SK037",
    item_type: "course",
    title: "React Native Official Docs and Tutorial",
    description: "Free official tutorial from the React Native documentation.",
    url: "https://reactnative.dev/docs/getting-started",
    difficulty: "intermediate",
    estimated_hours: 15,
    is_active: true,
  },
  {
    rec_id: "RC061",
    skill_id: "SK038",
    item_type: "course",
    title: "Flutter Official Codelabs",
    description: "Free hands-on Flutter tutorials from the Flutter team.",
    url: "https://docs.flutter.dev/codelabs",
    difficulty: "intermediate",
    estimated_hours: 20,
    is_active: true,
  },
];
