// =============================================================================
// FROM CAMPUS TO CAREER – TAXONOMY SEED
// Auto-generated from from_campus_to_career_taxonomy_seed.xlsx
// Replace SK*/CR*/SA*/RA*/RC* reference IDs with UUIDs in production.
// =============================================================================

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SkillCategory =
  | "Programming Languages"
  | "Web Development"
  | "Mobile Development"
  | "Databases"
  | "Data Science & Analytics"
  | "Cloud & DevOps"
  | "Cybersecurity"
  | "Networking"
  | "Software Engineering"
  | "IT Support & Systems"
  | "Professional Skills"
  | "UI/UX & Design";

export type RoleCategory =
  | "Software Development"
  | "Data & Analytics"
  | "Cloud & DevOps"
  | "Cybersecurity"
  | "Networking"
  | "IT Support"
  | "UI/UX"
  | "Quality Assurance"
  | "Project Management"
  | "Specialized";

export type ItemType = "course" | "project" | "certification" | "internship";
export type Difficulty = "beginner" | "intermediate" | "advanced";

export interface Skill {
  skill_id: string;
  name: string;
  category: SkillCategory;
  is_active: boolean;
  notes: string;
}

export interface SkillAlias {
  alias_id: string;
  skill_id: string;
  alias: string;
  source: string;
  reviewed: boolean;
  notes: string;
}

export interface CareerRole {
  role_id: string;
  title: string;
  description: string;
  is_active: boolean;
  category: RoleCategory;
}

export interface CareerRoleAlias {
  alias_id: string;
  role_id: string;
  alias: string;
  normalized_alias: string;
  notes: string;
}

// ---------------------------------------------------------------------------
// Skills (133 records)
// ---------------------------------------------------------------------------

export const skills: Skill[] = [
  {
    skill_id: "SK001",
    name: "Python",
    category: "Programming Languages",
    is_active: true,
    notes:
      "General-purpose; widely used in data science, automation, and backend",
  },
  {
    skill_id: "SK002",
    name: "Java",
    category: "Programming Languages",
    is_active: true,
    notes: "Enterprise backend; Android development",
  },
  {
    skill_id: "SK003",
    name: "JavaScript",
    category: "Programming Languages",
    is_active: true,
    notes: "Web frontend and Node.js backend",
  },
  {
    skill_id: "SK004",
    name: "TypeScript",
    category: "Programming Languages",
    is_active: true,
    notes: "Typed superset of JavaScript",
  },
  {
    skill_id: "SK005",
    name: "C",
    category: "Programming Languages",
    is_active: true,
    notes: "Systems programming; embedded; taught in most BSCS programs",
  },
  {
    skill_id: "SK006",
    name: "C++",
    category: "Programming Languages",
    is_active: true,
    notes: "Systems, game dev, competitive programming",
  },
  {
    skill_id: "SK007",
    name: "C#",
    category: "Programming Languages",
    is_active: true,
    notes: ".NET ecosystem; game dev with Unity",
  },
  {
    skill_id: "SK008",
    name: "PHP",
    category: "Programming Languages",
    is_active: true,
    notes: "Web development; dominant in PH freelance market",
  },
  {
    skill_id: "SK009",
    name: "Kotlin",
    category: "Programming Languages",
    is_active: true,
    notes: "Modern Android development",
  },
  {
    skill_id: "SK010",
    name: "Swift",
    category: "Programming Languages",
    is_active: false,
    notes: "iOS; limited PH market relevance",
  },
  {
    skill_id: "SK011",
    name: "Go",
    category: "Programming Languages",
    is_active: true,
    notes: "Cloud-native backend services",
  },
  {
    skill_id: "SK012",
    name: "Rust",
    category: "Programming Languages",
    is_active: false,
    notes: "Systems programming; emerging",
  },
  {
    skill_id: "SK013",
    name: "R",
    category: "Programming Languages",
    is_active: true,
    notes: "Statistical computing; data analysis",
  },
  {
    skill_id: "SK014",
    name: "MATLAB",
    category: "Programming Languages",
    is_active: false,
    notes: "Academic engineering; limited industry use",
  },
  {
    skill_id: "SK015",
    name: "Shell Scripting",
    category: "Programming Languages",
    is_active: true,
    notes: "Bash/Zsh; automation and DevOps",
  },
  {
    skill_id: "SK016",
    name: "SQL",
    category: "Programming Languages",
    is_active: true,
    notes: "Relational database querying; universal skill",
  },
  {
    skill_id: "SK017",
    name: "HTML",
    category: "Web Development",
    is_active: true,
    notes: "Markup language for web pages",
  },
  {
    skill_id: "SK018",
    name: "CSS",
    category: "Web Development",
    is_active: true,
    notes: "Styling for web pages",
  },
  {
    skill_id: "SK019",
    name: "React",
    category: "Web Development",
    is_active: true,
    notes: "Frontend JavaScript UI library",
  },
  {
    skill_id: "SK020",
    name: "Next.js",
    category: "Web Development",
    is_active: true,
    notes: "React meta-framework; SSR and SSG",
  },
  {
    skill_id: "SK021",
    name: "Vue.js",
    category: "Web Development",
    is_active: true,
    notes: "Progressive frontend framework",
  },
  {
    skill_id: "SK022",
    name: "Angular",
    category: "Web Development",
    is_active: true,
    notes: "Enterprise frontend framework by Google",
  },
  {
    skill_id: "SK023",
    name: "Node.js",
    category: "Web Development",
    is_active: true,
    notes: "JavaScript runtime for backend",
  },
  {
    skill_id: "SK024",
    name: "Express.js",
    category: "Web Development",
    is_active: true,
    notes: "Minimal Node.js web framework",
  },
  {
    skill_id: "SK025",
    name: "REST API Design",
    category: "Web Development",
    is_active: true,
    notes: "Designing and consuming RESTful APIs",
  },
  {
    skill_id: "SK026",
    name: "GraphQL",
    category: "Web Development",
    is_active: true,
    notes: "Query language for APIs",
  },
  {
    skill_id: "SK027",
    name: "Laravel",
    category: "Web Development",
    is_active: true,
    notes: "PHP framework; popular in PH",
  },
  {
    skill_id: "SK028",
    name: "Django",
    category: "Web Development",
    is_active: true,
    notes: "Python web framework",
  },
  {
    skill_id: "SK029",
    name: "FastAPI",
    category: "Web Development",
    is_active: true,
    notes: "Modern Python API framework",
  },
  {
    skill_id: "SK030",
    name: "Spring Boot",
    category: "Web Development",
    is_active: true,
    notes: "Java enterprise web framework",
  },
  {
    skill_id: "SK031",
    name: "Tailwind CSS",
    category: "Web Development",
    is_active: true,
    notes: "Utility-first CSS framework",
  },
  {
    skill_id: "SK032",
    name: "Bootstrap",
    category: "Web Development",
    is_active: true,
    notes: "CSS component library",
  },
  {
    skill_id: "SK033",
    name: "Responsive Web Design",
    category: "Web Development",
    is_active: true,
    notes: "Mobile-first design practices",
  },
  {
    skill_id: "SK034",
    name: "Web Accessibility",
    category: "Web Development",
    is_active: true,
    notes: "WCAG standards; inclusive design",
  },
  {
    skill_id: "SK035",
    name: "Android Development",
    category: "Mobile Development",
    is_active: true,
    notes: "Native Android apps using Java or Kotlin",
  },
  {
    skill_id: "SK036",
    name: "iOS Development",
    category: "Mobile Development",
    is_active: false,
    notes: "Native iOS apps; limited PH relevance",
  },
  {
    skill_id: "SK037",
    name: "React Native",
    category: "Mobile Development",
    is_active: true,
    notes: "Cross-platform mobile using React",
  },
  {
    skill_id: "SK038",
    name: "Flutter",
    category: "Mobile Development",
    is_active: true,
    notes: "Cross-platform mobile using Dart",
  },
  {
    skill_id: "SK039",
    name: "Expo",
    category: "Mobile Development",
    is_active: true,
    notes: "React Native toolchain and deployment",
  },
  {
    skill_id: "SK040",
    name: "PostgreSQL",
    category: "Databases",
    is_active: true,
    notes: "Advanced open-source relational database",
  },
  {
    skill_id: "SK041",
    name: "MySQL",
    category: "Databases",
    is_active: true,
    notes: "Widely used relational database",
  },
  {
    skill_id: "SK042",
    name: "SQLite",
    category: "Databases",
    is_active: true,
    notes: "Embedded relational database",
  },
  {
    skill_id: "SK043",
    name: "MongoDB",
    category: "Databases",
    is_active: true,
    notes: "Document-based NoSQL database",
  },
  {
    skill_id: "SK044",
    name: "Redis",
    category: "Databases",
    is_active: true,
    notes: "In-memory cache and data structure store",
  },
  {
    skill_id: "SK045",
    name: "Firebase Firestore",
    category: "Databases",
    is_active: true,
    notes: "Cloud NoSQL database by Google",
  },
  {
    skill_id: "SK046",
    name: "Supabase",
    category: "Databases",
    is_active: true,
    notes: "Open-source Firebase alternative on Postgres",
  },
  {
    skill_id: "SK047",
    name: "Database Design",
    category: "Databases",
    is_active: true,
    notes: "Entity-relationship modeling; normalization",
  },
  {
    skill_id: "SK048",
    name: "Database Indexing",
    category: "Databases",
    is_active: true,
    notes: "Query optimization through indexes",
  },
  {
    skill_id: "SK049",
    name: "ORM Usage",
    category: "Databases",
    is_active: true,
    notes: "Using ORMs like Drizzle, Prisma, SQLAlchemy",
  },
  {
    skill_id: "SK050",
    name: "Data Migration",
    category: "Databases",
    is_active: true,
    notes: "Schema versioning and data migration",
  },
  {
    skill_id: "SK051",
    name: "Data Analysis",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Exploratory data analysis; statistics",
  },
  {
    skill_id: "SK052",
    name: "Machine Learning",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Supervised and unsupervised ML models",
  },
  {
    skill_id: "SK053",
    name: "Deep Learning",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Neural networks; CNNs; RNNs",
  },
  {
    skill_id: "SK054",
    name: "Natural Language Processing",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Text processing; NLP pipelines",
  },
  {
    skill_id: "SK055",
    name: "Data Visualization",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Charts and dashboards; Matplotlib; Seaborn; Plotly",
  },
  {
    skill_id: "SK056",
    name: "Pandas",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Python data manipulation library",
  },
  {
    skill_id: "SK057",
    name: "NumPy",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Numerical computing with Python",
  },
  {
    skill_id: "SK058",
    name: "Scikit-learn",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "ML library for Python",
  },
  {
    skill_id: "SK059",
    name: "TensorFlow",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Deep learning framework by Google",
  },
  {
    skill_id: "SK060",
    name: "PyTorch",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Deep learning framework by Meta",
  },
  {
    skill_id: "SK061",
    name: "Data Wrangling",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Cleaning and transforming raw data",
  },
  {
    skill_id: "SK062",
    name: "Feature Engineering",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Creating features for ML models",
  },
  {
    skill_id: "SK063",
    name: "Model Evaluation",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Metrics; cross-validation; overfitting detection",
  },
  {
    skill_id: "SK064",
    name: "Statistical Analysis",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Hypothesis testing; regression; probability",
  },
  {
    skill_id: "SK065",
    name: "Business Intelligence",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "BI tools; dashboards; reporting",
  },
  {
    skill_id: "SK066",
    name: "Power BI",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Microsoft BI dashboard tool",
  },
  {
    skill_id: "SK067",
    name: "Tableau",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Visual analytics platform",
  },
  {
    skill_id: "SK068",
    name: "ETL Pipelines",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Extract, transform, load workflows",
  },
  {
    skill_id: "SK069",
    name: "Data Warehousing",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "BigQuery; Redshift; Snowflake concepts",
  },
  {
    skill_id: "SK070",
    name: "Polars",
    category: "Data Science & Analytics",
    is_active: true,
    notes: "Fast Rust-based dataframe library for Python",
  },
  {
    skill_id: "SK071",
    name: "Cloud Computing Fundamentals",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Core concepts: IaaS, PaaS, SaaS",
  },
  {
    skill_id: "SK072",
    name: "AWS",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Amazon Web Services cloud platform",
  },
  {
    skill_id: "SK073",
    name: "Google Cloud Platform",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "GCP services and tools",
  },
  {
    skill_id: "SK074",
    name: "Microsoft Azure",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Azure cloud services",
  },
  {
    skill_id: "SK075",
    name: "Docker",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Containerization platform",
  },
  {
    skill_id: "SK076",
    name: "Kubernetes",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Container orchestration system",
  },
  {
    skill_id: "SK077",
    name: "CI/CD",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Continuous integration and deployment pipelines",
  },
  {
    skill_id: "SK078",
    name: "GitHub Actions",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "CI/CD automation with GitHub",
  },
  {
    skill_id: "SK079",
    name: "Infrastructure as Code",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Terraform; Pulumi; cloud provisioning",
  },
  {
    skill_id: "SK080",
    name: "Linux Administration",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Linux OS management and shell usage",
  },
  {
    skill_id: "SK081",
    name: "Nginx",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Web server and reverse proxy",
  },
  {
    skill_id: "SK082",
    name: "Monitoring & Observability",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Logging; metrics; alerting; Sentry; Datadog",
  },
  {
    skill_id: "SK083",
    name: "Serverless Architecture",
    category: "Cloud & DevOps",
    is_active: true,
    notes: "Functions as a service; cloud-native design",
  },
  {
    skill_id: "SK084",
    name: "Network Security",
    category: "Cybersecurity",
    is_active: true,
    notes: "Firewalls; VPNs; network protocols",
  },
  {
    skill_id: "SK085",
    name: "Ethical Hacking",
    category: "Cybersecurity",
    is_active: true,
    notes: "Penetration testing; vulnerability assessment",
  },
  {
    skill_id: "SK086",
    name: "Cryptography",
    category: "Cybersecurity",
    is_active: true,
    notes: "Encryption; hashing; PKI",
  },
  {
    skill_id: "SK087",
    name: "Web Application Security",
    category: "Cybersecurity",
    is_active: true,
    notes: "OWASP Top 10; XSS; SQLi; CSRF",
  },
  {
    skill_id: "SK088",
    name: "Incident Response",
    category: "Cybersecurity",
    is_active: true,
    notes: "Handling and recovering from security incidents",
  },
  {
    skill_id: "SK089",
    name: "Security Auditing",
    category: "Cybersecurity",
    is_active: true,
    notes: "Assessing systems for compliance and vulnerabilities",
  },
  {
    skill_id: "SK090",
    name: "Identity & Access Management",
    category: "Cybersecurity",
    is_active: true,
    notes: "Auth, OAuth, SSO, RBAC",
  },
  {
    skill_id: "SK091",
    name: "SIEM Tools",
    category: "Cybersecurity",
    is_active: true,
    notes: "Splunk; IBM QRadar; log monitoring",
  },
  {
    skill_id: "SK092",
    name: "Malware Analysis",
    category: "Cybersecurity",
    is_active: false,
    notes: "Reverse engineering; sandboxing",
  },
  {
    skill_id: "SK093",
    name: "Secure Coding Practices",
    category: "Cybersecurity",
    is_active: true,
    notes: "Writing secure and resilient code",
  },
  {
    skill_id: "SK094",
    name: "Computer Networking Fundamentals",
    category: "Networking",
    is_active: true,
    notes: "OSI model; TCP/IP; subnetting",
  },
  {
    skill_id: "SK095",
    name: "Network Protocols",
    category: "Networking",
    is_active: true,
    notes: "HTTP; DNS; DHCP; FTP; SMTP",
  },
  {
    skill_id: "SK096",
    name: "Network Administration",
    category: "Networking",
    is_active: true,
    notes: "Router/switch config; network management",
  },
  {
    skill_id: "SK097",
    name: "Wireless Networks",
    category: "Networking",
    is_active: true,
    notes: "Wi-Fi standards; 802.11; mobile networks",
  },
  {
    skill_id: "SK098",
    name: "Network Troubleshooting",
    category: "Networking",
    is_active: true,
    notes: "Diagnosing and resolving connectivity issues",
  },
  {
    skill_id: "SK099",
    name: "VoIP & Unified Communications",
    category: "Networking",
    is_active: false,
    notes: "Voice over IP systems",
  },
  {
    skill_id: "SK100",
    name: "Object-Oriented Programming",
    category: "Software Engineering",
    is_active: true,
    notes: "OOP principles: encapsulation, inheritance, polymorphism",
  },
  {
    skill_id: "SK101",
    name: "Functional Programming",
    category: "Software Engineering",
    is_active: true,
    notes: "Pure functions; immutability; composition",
  },
  {
    skill_id: "SK102",
    name: "Design Patterns",
    category: "Software Engineering",
    is_active: true,
    notes: "GoF patterns; architectural patterns",
  },
  {
    skill_id: "SK103",
    name: "Data Structures",
    category: "Software Engineering",
    is_active: true,
    notes: "Arrays; linked lists; trees; graphs; heaps",
  },
  {
    skill_id: "SK104",
    name: "Algorithms",
    category: "Software Engineering",
    is_active: true,
    notes: "Sorting; searching; dynamic programming; complexity",
  },
  {
    skill_id: "SK105",
    name: "System Design",
    category: "Software Engineering",
    is_active: true,
    notes: "Scalable architecture; distributed systems thinking",
  },
  {
    skill_id: "SK106",
    name: "Software Testing",
    category: "Software Engineering",
    is_active: true,
    notes: "Unit; integration; e2e testing",
  },
  {
    skill_id: "SK107",
    name: "Test-Driven Development",
    category: "Software Engineering",
    is_active: true,
    notes: "Writing tests before code",
  },
  {
    skill_id: "SK108",
    name: "Code Review",
    category: "Software Engineering",
    is_active: true,
    notes: "Reading and reviewing code for quality",
  },
  {
    skill_id: "SK109",
    name: "Technical Documentation",
    category: "Software Engineering",
    is_active: true,
    notes: "Writing clear technical specs and docs",
  },
  {
    skill_id: "SK110",
    name: "Agile Methodology",
    category: "Software Engineering",
    is_active: true,
    notes: "Scrum; Kanban; sprint planning",
  },
  {
    skill_id: "SK111",
    name: "Version Control (Git)",
    category: "Software Engineering",
    is_active: true,
    notes: "Git branching; pull requests; workflows",
  },
  {
    skill_id: "SK112",
    name: "Clean Code Principles",
    category: "Software Engineering",
    is_active: true,
    notes: "SOLID; DRY; KISS; readable code",
  },
  {
    skill_id: "SK113",
    name: "API Integration",
    category: "Software Engineering",
    is_active: true,
    notes: "Consuming third-party APIs",
  },
  {
    skill_id: "SK114",
    name: "Monorepo Management",
    category: "Software Engineering",
    is_active: true,
    notes: "Turborepo; Nx; managing multi-package repos",
  },
  {
    skill_id: "SK115",
    name: "Technical Support",
    category: "IT Support & Systems",
    is_active: true,
    notes: "Helpdesk; troubleshooting hardware and software",
  },
  {
    skill_id: "SK116",
    name: "Hardware Troubleshooting",
    category: "IT Support & Systems",
    is_active: true,
    notes: "Diagnosing and repairing computer hardware",
  },
  {
    skill_id: "SK117",
    name: "Operating Systems",
    category: "IT Support & Systems",
    is_active: true,
    notes: "Windows; Linux; macOS administration",
  },
  {
    skill_id: "SK118",
    name: "IT Service Management",
    category: "IT Support & Systems",
    is_active: true,
    notes: "ITIL; ticketing systems; SLA management",
  },
  {
    skill_id: "SK119",
    name: "Active Directory",
    category: "IT Support & Systems",
    is_active: true,
    notes: "Windows domain management; user provisioning",
  },
  {
    skill_id: "SK120",
    name: "Virtualization",
    category: "IT Support & Systems",
    is_active: true,
    notes: "VMware; VirtualBox; Hyper-V",
  },
  {
    skill_id: "SK121",
    name: "Project Management",
    category: "Professional Skills",
    is_active: true,
    notes: "Planning; scheduling; resource management",
  },
  {
    skill_id: "SK122",
    name: "Communication Skills",
    category: "Professional Skills",
    is_active: true,
    notes: "Written and verbal communication",
  },
  {
    skill_id: "SK123",
    name: "Critical Thinking",
    category: "Professional Skills",
    is_active: true,
    notes: "Problem analysis and decision-making",
  },
  {
    skill_id: "SK124",
    name: "Time Management",
    category: "Professional Skills",
    is_active: true,
    notes: "Prioritization; meeting deadlines",
  },
  {
    skill_id: "SK125",
    name: "Teamwork & Collaboration",
    category: "Professional Skills",
    is_active: true,
    notes: "Working effectively in teams",
  },
  {
    skill_id: "SK126",
    name: "Problem Solving",
    category: "Professional Skills",
    is_active: true,
    notes: "Structured approach to resolving complex issues",
  },
  {
    skill_id: "SK127",
    name: "Presentation Skills",
    category: "Professional Skills",
    is_active: true,
    notes: "Delivering clear and engaging presentations",
  },
  {
    skill_id: "SK128",
    name: "UI Design",
    category: "UI/UX & Design",
    is_active: true,
    notes: "Visual interface design; layout; typography",
  },
  {
    skill_id: "SK129",
    name: "UX Research",
    category: "UI/UX & Design",
    is_active: true,
    notes: "User interviews; usability testing; personas",
  },
  {
    skill_id: "SK130",
    name: "Wireframing & Prototyping",
    category: "UI/UX & Design",
    is_active: true,
    notes: "Figma; Adobe XD; low and high fidelity prototypes",
  },
  {
    skill_id: "SK131",
    name: "Figma",
    category: "UI/UX & Design",
    is_active: true,
    notes: "Collaborative UI design tool",
  },
  {
    skill_id: "SK132",
    name: "Design Systems",
    category: "UI/UX & Design",
    is_active: true,
    notes: "Component libraries; design tokens; style guides",
  },
  {
    skill_id: "SK133",
    name: "User Testing",
    category: "UI/UX & Design",
    is_active: true,
    notes: "Validating designs with real users",
  },
];

// ---------------------------------------------------------------------------
// Skill Aliases (152 records)
// ---------------------------------------------------------------------------

export const skillAliases: SkillAlias[] = [
  {
    alias_id: "SA001",
    skill_id: "SK001",
    alias: "py",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA002",
    skill_id: "SK001",
    alias: "python3",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA003",
    skill_id: "SK001",
    alias: "python programming",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA004",
    skill_id: "SK002",
    alias: "java programming",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA005",
    skill_id: "SK002",
    alias: "core java",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA006",
    skill_id: "SK002",
    alias: "java ee",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA007",
    skill_id: "SK002",
    alias: "jakarta ee",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA008",
    skill_id: "SK003",
    alias: "js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA009",
    skill_id: "SK003",
    alias: "javascript es6",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA010",
    skill_id: "SK003",
    alias: "ecmascript",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA011",
    skill_id: "SK003",
    alias: "vanilla js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA012",
    skill_id: "SK004",
    alias: "ts",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA013",
    skill_id: "SK004",
    alias: "typescript programming",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA014",
    skill_id: "SK005",
    alias: "c programming",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA015",
    skill_id: "SK005",
    alias: "c language",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA016",
    skill_id: "SK006",
    alias: "cpp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA017",
    skill_id: "SK006",
    alias: "c plus plus",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA018",
    skill_id: "SK007",
    alias: "csharp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA019",
    skill_id: "SK007",
    alias: "c sharp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA020",
    skill_id: "SK007",
    alias: "dotnet",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA021",
    skill_id: "SK007",
    alias: ".net",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA022",
    skill_id: "SK008",
    alias: "php programming",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA023",
    skill_id: "SK008",
    alias: "php development",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA024",
    skill_id: "SK016",
    alias: "structured query language",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA025",
    skill_id: "SK016",
    alias: "sql queries",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA026",
    skill_id: "SK016",
    alias: "mysql",
    source: "job_postings",
    reviewed: true,
    notes: "Maps to SQL skill; MySQL is a db product",
  },
  {
    alias_id: "SA027",
    skill_id: "SK016",
    alias: "t-sql",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA028",
    skill_id: "SK016",
    alias: "plsql",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA029",
    skill_id: "SK017",
    alias: "html5",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA030",
    skill_id: "SK017",
    alias: "hypertext markup",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA031",
    skill_id: "SK018",
    alias: "css3",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA032",
    skill_id: "SK018",
    alias: "cascading style sheets",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA033",
    skill_id: "SK018",
    alias: "sass",
    source: "job_postings",
    reviewed: true,
    notes: "CSS preprocessor",
  },
  {
    alias_id: "SA034",
    skill_id: "SK018",
    alias: "scss",
    source: "job_postings",
    reviewed: true,
    notes: "CSS preprocessor",
  },
  {
    alias_id: "SA035",
    skill_id: "SK019",
    alias: "reactjs",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA036",
    skill_id: "SK019",
    alias: "react.js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA037",
    skill_id: "SK019",
    alias: "react frontend",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA038",
    skill_id: "SK020",
    alias: "nextjs",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA039",
    skill_id: "SK020",
    alias: "next js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA040",
    skill_id: "SK021",
    alias: "vuejs",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA041",
    skill_id: "SK021",
    alias: "vue.js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA042",
    skill_id: "SK021",
    alias: "vue 3",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA043",
    skill_id: "SK022",
    alias: "angularjs",
    source: "job_postings",
    reviewed: true,
    notes: "Note: AngularJS is legacy; Angular 2+ is different",
  },
  {
    alias_id: "SA044",
    skill_id: "SK022",
    alias: "angular framework",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA045",
    skill_id: "SK023",
    alias: "nodejs",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA046",
    skill_id: "SK023",
    alias: "node js",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA047",
    skill_id: "SK025",
    alias: "restful api",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA048",
    skill_id: "SK025",
    alias: "rest services",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA049",
    skill_id: "SK025",
    alias: "api development",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA050",
    skill_id: "SK025",
    alias: "web services",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA051",
    skill_id: "SK027",
    alias: "laravel framework",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA052",
    skill_id: "SK027",
    alias: "laravel php",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA053",
    skill_id: "SK028",
    alias: "django rest framework",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA054",
    skill_id: "SK028",
    alias: "drf",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA055",
    skill_id: "SK030",
    alias: "spring",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA056",
    skill_id: "SK030",
    alias: "spring framework",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA057",
    skill_id: "SK030",
    alias: "spring mvc",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA058",
    skill_id: "SK037",
    alias: "rn",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA059",
    skill_id: "SK037",
    alias: "react native mobile",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA060",
    skill_id: "SK038",
    alias: "flutter dart",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA061",
    skill_id: "SK038",
    alias: "dart flutter",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA062",
    skill_id: "SK040",
    alias: "postgres",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA063",
    skill_id: "SK040",
    alias: "postgresql database",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA064",
    skill_id: "SK043",
    alias: "mongo",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA065",
    skill_id: "SK043",
    alias: "mongodb database",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA066",
    skill_id: "SK043",
    alias: "nosql",
    source: "job_postings",
    reviewed: false,
    notes: "Broad term; may map to other NoSQL dbs too",
  },
  {
    alias_id: "SA067",
    skill_id: "SK044",
    alias: "redis cache",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA068",
    skill_id: "SK044",
    alias: "redis db",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA069",
    skill_id: "SK052",
    alias: "ml",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA070",
    skill_id: "SK052",
    alias: "machine learning algorithms",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA071",
    skill_id: "SK052",
    alias: "predictive modeling",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA072",
    skill_id: "SK052",
    alias: "supervised learning",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA073",
    skill_id: "SK052",
    alias: "unsupervised learning",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA074",
    skill_id: "SK053",
    alias: "dl",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA075",
    skill_id: "SK053",
    alias: "neural networks",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA076",
    skill_id: "SK053",
    alias: "artificial neural networks",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA077",
    skill_id: "SK054",
    alias: "nlp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA078",
    skill_id: "SK054",
    alias: "text analytics",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA079",
    skill_id: "SK054",
    alias: "natural language understanding",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA080",
    skill_id: "SK055",
    alias: "data viz",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA081",
    skill_id: "SK055",
    alias: "matplotlib",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA082",
    skill_id: "SK055",
    alias: "seaborn",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA083",
    skill_id: "SK055",
    alias: "plotly",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA084",
    skill_id: "SK056",
    alias: "pandas dataframe",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA085",
    skill_id: "SK075",
    alias: "containerization",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA086",
    skill_id: "SK075",
    alias: "docker container",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA087",
    skill_id: "SK075",
    alias: "dockerfile",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA088",
    skill_id: "SK076",
    alias: "k8s",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA089",
    skill_id: "SK076",
    alias: "kubernetes orchestration",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA090",
    skill_id: "SK077",
    alias: "continuous integration",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA091",
    skill_id: "SK077",
    alias: "continuous deployment",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA092",
    skill_id: "SK077",
    alias: "devops pipeline",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA093",
    skill_id: "SK077",
    alias: "jenkins",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA094",
    skill_id: "SK077",
    alias: "gitlab ci",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA095",
    skill_id: "SK072",
    alias: "amazon web services",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA096",
    skill_id: "SK072",
    alias: "aws cloud",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA097",
    skill_id: "SK073",
    alias: "gcp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA098",
    skill_id: "SK073",
    alias: "google cloud",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA099",
    skill_id: "SK074",
    alias: "azure cloud",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA100",
    skill_id: "SK074",
    alias: "microsoft azure",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA101",
    skill_id: "SK080",
    alias: "linux",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA102",
    skill_id: "SK080",
    alias: "ubuntu",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA103",
    skill_id: "SK080",
    alias: "unix",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA104",
    skill_id: "SK111",
    alias: "git",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA105",
    skill_id: "SK111",
    alias: "github",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA106",
    skill_id: "SK111",
    alias: "gitlab",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA107",
    skill_id: "SK111",
    alias: "version control",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA108",
    skill_id: "SK111",
    alias: "source control",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA109",
    skill_id: "SK100",
    alias: "oop",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA110",
    skill_id: "SK100",
    alias: "object oriented design",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA111",
    skill_id: "SK103",
    alias: "dsa",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA112",
    skill_id: "SK103",
    alias: "data structures and algorithms",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA113",
    skill_id: "SK105",
    alias: "distributed systems",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA114",
    skill_id: "SK105",
    alias: "scalable system design",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA115",
    skill_id: "SK105",
    alias: "high level design",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA116",
    skill_id: "SK106",
    alias: "unit testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA117",
    skill_id: "SK106",
    alias: "integration testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA118",
    skill_id: "SK106",
    alias: "qa testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA119",
    skill_id: "SK106",
    alias: "quality assurance",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA120",
    skill_id: "SK106",
    alias: "automated testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA121",
    skill_id: "SK110",
    alias: "scrum",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA122",
    skill_id: "SK110",
    alias: "kanban",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA123",
    skill_id: "SK110",
    alias: "agile development",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA124",
    skill_id: "SK110",
    alias: "sprint planning",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA125",
    skill_id: "SK085",
    alias: "pen testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA126",
    skill_id: "SK085",
    alias: "penetration testing",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA127",
    skill_id: "SK085",
    alias: "ethical hacker",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA128",
    skill_id: "SK087",
    alias: "owasp",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA129",
    skill_id: "SK087",
    alias: "web security",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA130",
    skill_id: "SK084",
    alias: "firewall management",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA131",
    skill_id: "SK084",
    alias: "network defense",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA132",
    skill_id: "SK115",
    alias: "helpdesk",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA133",
    skill_id: "SK115",
    alias: "help desk",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA134",
    skill_id: "SK115",
    alias: "it support specialist",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA135",
    skill_id: "SK115",
    alias: "desktop support",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA136",
    skill_id: "SK118",
    alias: "itil",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA137",
    skill_id: "SK118",
    alias: "service desk",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA138",
    skill_id: "SK131",
    alias: "figma design",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA139",
    skill_id: "SK131",
    alias: "figma prototyping",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA140",
    skill_id: "SK094",
    alias: "tcp/ip",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA141",
    skill_id: "SK094",
    alias: "osi model",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA142",
    skill_id: "SK094",
    alias: "computer networks",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA143",
    skill_id: "SK068",
    alias: "etl",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA144",
    skill_id: "SK068",
    alias: "data pipeline",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA145",
    skill_id: "SK068",
    alias: "data engineering",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA146",
    skill_id: "SK066",
    alias: "powerbi",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA147",
    skill_id: "SK066",
    alias: "power bi dashboard",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA148",
    skill_id: "SK065",
    alias: "bi reporting",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA149",
    skill_id: "SK065",
    alias: "business analytics",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA150",
    skill_id: "SK015",
    alias: "bash scripting",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA151",
    skill_id: "SK015",
    alias: "bash",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
  {
    alias_id: "SA152",
    skill_id: "SK015",
    alias: "shell script",
    source: "job_postings",
    reviewed: true,
    notes: "",
  },
];

// ---------------------------------------------------------------------------
// Career Roles (40 records)
// ---------------------------------------------------------------------------

export const careerRoles: CareerRole[] = [
  {
    role_id: "CR001",
    title: "Software Developer",
    description:
      "Designs, builds, and maintains software applications using various programming languages and frameworks.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR002",
    title: "Frontend Developer",
    description:
      "Builds user-facing web interfaces using HTML, CSS, JavaScript, and modern UI frameworks.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR003",
    title: "Backend Developer",
    description:
      "Develops server-side logic, APIs, and database integrations for web and mobile applications.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR004",
    title: "Full Stack Developer",
    description:
      "Works across both frontend and backend layers of a web application.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR005",
    title: "Mobile Developer",
    description:
      "Builds native or cross-platform mobile applications for Android and/or iOS.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR006",
    title: "Android Developer",
    description: "Develops native Android applications using Java or Kotlin.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR007",
    title: "iOS Developer",
    description: "Develops native iOS applications using Swift or Objective-C.",
    is_active: false,
    category: "Software Development",
  },
  {
    role_id: "CR008",
    title: "Junior Software Developer",
    description:
      "Entry-level software developer working under supervision on coding tasks.",
    is_active: true,
    category: "Software Development",
  },
  {
    role_id: "CR009",
    title: "Data Analyst",
    description:
      "Analyzes datasets to extract insights, build reports, and support business decisions.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR010",
    title: "Data Scientist",
    description:
      "Builds predictive and analytical models using machine learning and statistical methods.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR011",
    title: "Data Engineer",
    description:
      "Designs and maintains data pipelines, ETL processes, and data infrastructure.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR012",
    title: "Business Intelligence Analyst",
    description:
      "Creates dashboards, KPIs, and reports to support business decision-making.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR013",
    title: "Machine Learning Engineer",
    description:
      "Develops, trains, and deploys machine learning models into production systems.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR014",
    title: "AI Engineer",
    description:
      "Builds AI-powered applications and integrates ML/LLM capabilities into products.",
    is_active: true,
    category: "Data & Analytics",
  },
  {
    role_id: "CR015",
    title: "DevOps Engineer",
    description:
      "Manages CI/CD pipelines, infrastructure automation, and cloud deployments.",
    is_active: true,
    category: "Cloud & DevOps",
  },
  {
    role_id: "CR016",
    title: "Cloud Engineer",
    description:
      "Designs and manages cloud infrastructure on AWS, GCP, or Azure.",
    is_active: true,
    category: "Cloud & DevOps",
  },
  {
    role_id: "CR017",
    title: "Site Reliability Engineer",
    description:
      "Ensures system reliability, scalability, and performance in production environments.",
    is_active: true,
    category: "Cloud & DevOps",
  },
  {
    role_id: "CR018",
    title: "Platform Engineer",
    description:
      "Builds internal developer platforms and tooling for engineering teams.",
    is_active: true,
    category: "Cloud & DevOps",
  },
  {
    role_id: "CR019",
    title: "Cybersecurity Analyst",
    description:
      "Monitors, detects, and responds to security threats and vulnerabilities.",
    is_active: true,
    category: "Cybersecurity",
  },
  {
    role_id: "CR020",
    title: "Penetration Tester",
    description:
      "Performs authorized ethical hacking to identify security weaknesses.",
    is_active: true,
    category: "Cybersecurity",
  },
  {
    role_id: "CR021",
    title: "Information Security Officer",
    description:
      "Manages organizational information security policies and compliance.",
    is_active: true,
    category: "Cybersecurity",
  },
  {
    role_id: "CR022",
    title: "Security Operations Center Analyst",
    description:
      "Monitors security events and responds to incidents in real-time.",
    is_active: true,
    category: "Cybersecurity",
  },
  {
    role_id: "CR023",
    title: "Network Engineer",
    description: "Designs and manages computer network infrastructure.",
    is_active: true,
    category: "Networking",
  },
  {
    role_id: "CR024",
    title: "Network Administrator",
    description:
      "Maintains and monitors network systems, connectivity, and performance.",
    is_active: true,
    category: "Networking",
  },
  {
    role_id: "CR025",
    title: "Systems Administrator",
    description: "Manages servers, operating systems, and IT infrastructure.",
    is_active: true,
    category: "Networking",
  },
  {
    role_id: "CR026",
    title: "IT Support Specialist",
    description:
      "Provides technical support to end users for hardware and software issues.",
    is_active: true,
    category: "IT Support",
  },
  {
    role_id: "CR027",
    title: "Technical Support Engineer",
    description:
      "Resolves complex technical issues and escalations for software or hardware.",
    is_active: true,
    category: "IT Support",
  },
  {
    role_id: "CR028",
    title: "Help Desk Technician",
    description: "Handles first-line IT support tickets and user queries.",
    is_active: true,
    category: "IT Support",
  },
  {
    role_id: "CR029",
    title: "UI/UX Designer",
    description:
      "Designs intuitive user interfaces and researches user experience needs.",
    is_active: true,
    category: "UI/UX",
  },
  {
    role_id: "CR030",
    title: "Product Designer",
    description:
      "Leads end-to-end design of digital products from research to high-fidelity UI.",
    is_active: true,
    category: "UI/UX",
  },
  {
    role_id: "CR031",
    title: "UX Researcher",
    description:
      "Conducts user research, usability testing, and synthesizes user insights.",
    is_active: true,
    category: "UI/UX",
  },
  {
    role_id: "CR032",
    title: "QA Engineer",
    description:
      "Tests software for bugs, regressions, and quality issues using manual and automated methods.",
    is_active: true,
    category: "Quality Assurance",
  },
  {
    role_id: "CR033",
    title: "Automation Test Engineer",
    description:
      "Writes and maintains automated test suites for software products.",
    is_active: true,
    category: "Quality Assurance",
  },
  {
    role_id: "CR034",
    title: "IT Project Manager",
    description:
      "Plans and manages IT projects, timelines, resources, and stakeholder communication.",
    is_active: true,
    category: "Project Management",
  },
  {
    role_id: "CR035",
    title: "Product Manager",
    description:
      "Owns product vision, roadmap, and prioritization for a digital product.",
    is_active: true,
    category: "Project Management",
  },
  {
    role_id: "CR036",
    title: "Scrum Master",
    description:
      "Facilitates agile ceremonies and removes impediments for development teams.",
    is_active: true,
    category: "Project Management",
  },
  {
    role_id: "CR037",
    title: "Blockchain Developer",
    description:
      "Builds decentralized applications and smart contracts on blockchain platforms.",
    is_active: false,
    category: "Specialized",
  },
  {
    role_id: "CR038",
    title: "Game Developer",
    description:
      "Creates video games using engines like Unity or Unreal Engine.",
    is_active: false,
    category: "Specialized",
  },
  {
    role_id: "CR039",
    title: "Embedded Systems Engineer",
    description: "Develops software for hardware devices and microcontrollers.",
    is_active: false,
    category: "Specialized",
  },
  {
    role_id: "CR040",
    title: "Research and Development Engineer",
    description:
      "Conducts technical research and prototypes innovative solutions.",
    is_active: true,
    category: "Specialized",
  },
];

// ---------------------------------------------------------------------------
// Career Role Aliases (126 records)
// ---------------------------------------------------------------------------

export const careerRoleAliases: CareerRoleAlias[] = [
  {
    alias_id: "RA001",
    role_id: "CR001",
    alias: "Software Engineer",
    normalized_alias: "software engineer",
    notes: "",
  },
  {
    alias_id: "RA002",
    role_id: "CR001",
    alias: "SWE",
    normalized_alias: "swe",
    notes: "",
  },
  {
    alias_id: "RA003",
    role_id: "CR001",
    alias: "Programmer",
    normalized_alias: "programmer",
    notes: "",
  },
  {
    alias_id: "RA004",
    role_id: "CR001",
    alias: "Coder",
    normalized_alias: "coder",
    notes: "",
  },
  {
    alias_id: "RA005",
    role_id: "CR001",
    alias: "Dev",
    normalized_alias: "dev",
    notes: "",
  },
  {
    alias_id: "RA006",
    role_id: "CR001",
    alias: "Developer",
    normalized_alias: "developer",
    notes: "",
  },
  {
    alias_id: "RA007",
    role_id: "CR001",
    alias: "Application Developer",
    normalized_alias: "application developer",
    notes: "",
  },
  {
    alias_id: "RA008",
    role_id: "CR001",
    alias: "Software Programmer",
    normalized_alias: "software programmer",
    notes: "",
  },
  {
    alias_id: "RA009",
    role_id: "CR001",
    alias: "Computer Programmer",
    normalized_alias: "computer programmer",
    notes: "",
  },
  {
    alias_id: "RA010",
    role_id: "CR002",
    alias: "Front-end Developer",
    normalized_alias: "front-end developer",
    notes: "",
  },
  {
    alias_id: "RA011",
    role_id: "CR002",
    alias: "Front End Developer",
    normalized_alias: "front end developer",
    notes: "",
  },
  {
    alias_id: "RA012",
    role_id: "CR002",
    alias: "Frontend Engineer",
    normalized_alias: "frontend engineer",
    notes: "",
  },
  {
    alias_id: "RA013",
    role_id: "CR002",
    alias: "UI Developer",
    normalized_alias: "ui developer",
    notes: "",
  },
  {
    alias_id: "RA014",
    role_id: "CR002",
    alias: "Web Developer",
    normalized_alias: "web developer",
    notes: "",
  },
  {
    alias_id: "RA015",
    role_id: "CR002",
    alias: "React Developer",
    normalized_alias: "react developer",
    notes: "",
  },
  {
    alias_id: "RA016",
    role_id: "CR002",
    alias: "Vue Developer",
    normalized_alias: "vue developer",
    notes: "",
  },
  {
    alias_id: "RA017",
    role_id: "CR002",
    alias: "Angular Developer",
    normalized_alias: "angular developer",
    notes: "",
  },
  {
    alias_id: "RA018",
    role_id: "CR002",
    alias: "JavaScript Developer",
    normalized_alias: "javascript developer",
    notes: "",
  },
  {
    alias_id: "RA019",
    role_id: "CR003",
    alias: "Back-end Developer",
    normalized_alias: "back-end developer",
    notes: "",
  },
  {
    alias_id: "RA020",
    role_id: "CR003",
    alias: "Backend Engineer",
    normalized_alias: "backend engineer",
    notes: "",
  },
  {
    alias_id: "RA021",
    role_id: "CR003",
    alias: "Server-side Developer",
    normalized_alias: "server-side developer",
    notes: "",
  },
  {
    alias_id: "RA022",
    role_id: "CR003",
    alias: "API Developer",
    normalized_alias: "api developer",
    notes: "",
  },
  {
    alias_id: "RA023",
    role_id: "CR003",
    alias: "Node Developer",
    normalized_alias: "node developer",
    notes: "",
  },
  {
    alias_id: "RA024",
    role_id: "CR003",
    alias: "PHP Developer",
    normalized_alias: "php developer",
    notes: "",
  },
  {
    alias_id: "RA025",
    role_id: "CR003",
    alias: "Java Developer",
    normalized_alias: "java developer",
    notes: "",
  },
  {
    alias_id: "RA026",
    role_id: "CR003",
    alias: "Python Developer",
    normalized_alias: "python developer",
    notes: "",
  },
  {
    alias_id: "RA027",
    role_id: "CR003",
    alias: "Laravel Developer",
    normalized_alias: "laravel developer",
    notes: "",
  },
  {
    alias_id: "RA028",
    role_id: "CR004",
    alias: "Full-Stack Developer",
    normalized_alias: "full-stack developer",
    notes: "",
  },
  {
    alias_id: "RA029",
    role_id: "CR004",
    alias: "Fullstack Developer",
    normalized_alias: "fullstack developer",
    notes: "",
  },
  {
    alias_id: "RA030",
    role_id: "CR004",
    alias: "Full Stack Engineer",
    normalized_alias: "full stack engineer",
    notes: "",
  },
  {
    alias_id: "RA031",
    role_id: "CR004",
    alias: "MEAN Developer",
    normalized_alias: "mean developer",
    notes: "MongoDB Express Angular Node",
  },
  {
    alias_id: "RA032",
    role_id: "CR004",
    alias: "MERN Developer",
    normalized_alias: "mern developer",
    notes: "MongoDB Express React Node",
  },
  {
    alias_id: "RA033",
    role_id: "CR004",
    alias: "LAMP Developer",
    normalized_alias: "lamp developer",
    notes: "Linux Apache MySQL PHP",
  },
  {
    alias_id: "RA034",
    role_id: "CR005",
    alias: "Mobile App Developer",
    normalized_alias: "mobile app developer",
    notes: "",
  },
  {
    alias_id: "RA035",
    role_id: "CR005",
    alias: "Mobile Engineer",
    normalized_alias: "mobile engineer",
    notes: "",
  },
  {
    alias_id: "RA036",
    role_id: "CR005",
    alias: "App Developer",
    normalized_alias: "app developer",
    notes: "",
  },
  {
    alias_id: "RA037",
    role_id: "CR005",
    alias: "Cross-platform Developer",
    normalized_alias: "cross-platform developer",
    notes: "",
  },
  {
    alias_id: "RA038",
    role_id: "CR005",
    alias: "React Native Developer",
    normalized_alias: "react native developer",
    notes: "",
  },
  {
    alias_id: "RA039",
    role_id: "CR005",
    alias: "Flutter Developer",
    normalized_alias: "flutter developer",
    notes: "",
  },
  {
    alias_id: "RA040",
    role_id: "CR006",
    alias: "Android App Developer",
    normalized_alias: "android app developer",
    notes: "",
  },
  {
    alias_id: "RA041",
    role_id: "CR006",
    alias: "Android Engineer",
    normalized_alias: "android engineer",
    notes: "",
  },
  {
    alias_id: "RA042",
    role_id: "CR006",
    alias: "Android Programmer",
    normalized_alias: "android programmer",
    notes: "",
  },
  {
    alias_id: "RA043",
    role_id: "CR006",
    alias: "Kotlin Developer",
    normalized_alias: "kotlin developer",
    notes: "",
  },
  {
    alias_id: "RA044",
    role_id: "CR009",
    alias: "Data Analytics Specialist",
    normalized_alias: "data analytics specialist",
    notes: "",
  },
  {
    alias_id: "RA045",
    role_id: "CR009",
    alias: "Business Analyst",
    normalized_alias: "business analyst",
    notes: "Overlap; context dependent",
  },
  {
    alias_id: "RA046",
    role_id: "CR009",
    alias: "Analytics Engineer",
    normalized_alias: "analytics engineer",
    notes: "",
  },
  {
    alias_id: "RA047",
    role_id: "CR009",
    alias: "Reporting Analyst",
    normalized_alias: "reporting analyst",
    notes: "",
  },
  {
    alias_id: "RA048",
    role_id: "CR009",
    alias: "Data Specialist",
    normalized_alias: "data specialist",
    notes: "",
  },
  {
    alias_id: "RA049",
    role_id: "CR010",
    alias: "Data Science Engineer",
    normalized_alias: "data science engineer",
    notes: "",
  },
  {
    alias_id: "RA050",
    role_id: "CR010",
    alias: "ML Researcher",
    normalized_alias: "ml researcher",
    notes: "",
  },
  {
    alias_id: "RA051",
    role_id: "CR010",
    alias: "AI Researcher",
    normalized_alias: "ai researcher",
    notes: "",
  },
  {
    alias_id: "RA052",
    role_id: "CR010",
    alias: "Statistician",
    normalized_alias: "statistician",
    notes: "",
  },
  {
    alias_id: "RA053",
    role_id: "CR010",
    alias: "Research Scientist",
    normalized_alias: "research scientist",
    notes: "",
  },
  {
    alias_id: "RA054",
    role_id: "CR011",
    alias: "Data Infrastructure Engineer",
    normalized_alias: "data infrastructure engineer",
    notes: "",
  },
  {
    alias_id: "RA055",
    role_id: "CR011",
    alias: "Big Data Engineer",
    normalized_alias: "big data engineer",
    notes: "",
  },
  {
    alias_id: "RA056",
    role_id: "CR011",
    alias: "ETL Developer",
    normalized_alias: "etl developer",
    notes: "",
  },
  {
    alias_id: "RA057",
    role_id: "CR011",
    alias: "Data Pipeline Engineer",
    normalized_alias: "data pipeline engineer",
    notes: "",
  },
  {
    alias_id: "RA058",
    role_id: "CR012",
    alias: "BI Developer",
    normalized_alias: "bi developer",
    notes: "",
  },
  {
    alias_id: "RA059",
    role_id: "CR012",
    alias: "BI Engineer",
    normalized_alias: "bi engineer",
    notes: "",
  },
  {
    alias_id: "RA060",
    role_id: "CR012",
    alias: "Reporting Specialist",
    normalized_alias: "reporting specialist",
    notes: "",
  },
  {
    alias_id: "RA061",
    role_id: "CR012",
    alias: "Dashboard Developer",
    normalized_alias: "dashboard developer",
    notes: "",
  },
  {
    alias_id: "RA062",
    role_id: "CR012",
    alias: "Power BI Developer",
    normalized_alias: "power bi developer",
    notes: "",
  },
  {
    alias_id: "RA063",
    role_id: "CR012",
    alias: "Tableau Developer",
    normalized_alias: "tableau developer",
    notes: "",
  },
  {
    alias_id: "RA064",
    role_id: "CR013",
    alias: "Machine Learning Developer",
    normalized_alias: "machine learning developer",
    notes: "",
  },
  {
    alias_id: "RA065",
    role_id: "CR013",
    alias: "ML Ops Engineer",
    normalized_alias: "ml ops engineer",
    notes: "",
  },
  {
    alias_id: "RA066",
    role_id: "CR013",
    alias: "MLOps Engineer",
    normalized_alias: "mlops engineer",
    notes: "",
  },
  {
    alias_id: "RA067",
    role_id: "CR013",
    alias: "AI Engineer",
    normalized_alias: "ai engineer",
    notes: "Overlaps with CR014",
  },
  {
    alias_id: "RA068",
    role_id: "CR015",
    alias: "DevOps Specialist",
    normalized_alias: "devops specialist",
    notes: "",
  },
  {
    alias_id: "RA069",
    role_id: "CR015",
    alias: "Release Engineer",
    normalized_alias: "release engineer",
    notes: "",
  },
  {
    alias_id: "RA070",
    role_id: "CR015",
    alias: "Build Engineer",
    normalized_alias: "build engineer",
    notes: "",
  },
  {
    alias_id: "RA071",
    role_id: "CR015",
    alias: "Infrastructure Engineer",
    normalized_alias: "infrastructure engineer",
    notes: "",
  },
  {
    alias_id: "RA072",
    role_id: "CR016",
    alias: "Cloud Solutions Architect",
    normalized_alias: "cloud solutions architect",
    notes: "",
  },
  {
    alias_id: "RA073",
    role_id: "CR016",
    alias: "AWS Engineer",
    normalized_alias: "aws engineer",
    notes: "",
  },
  {
    alias_id: "RA074",
    role_id: "CR016",
    alias: "Azure Engineer",
    normalized_alias: "azure engineer",
    notes: "",
  },
  {
    alias_id: "RA075",
    role_id: "CR016",
    alias: "GCP Engineer",
    normalized_alias: "gcp engineer",
    notes: "",
  },
  {
    alias_id: "RA076",
    role_id: "CR016",
    alias: "Cloud Architect",
    normalized_alias: "cloud architect",
    notes: "",
  },
  {
    alias_id: "RA077",
    role_id: "CR017",
    alias: "SRE",
    normalized_alias: "sre",
    notes: "",
  },
  {
    alias_id: "RA078",
    role_id: "CR017",
    alias: "Reliability Engineer",
    normalized_alias: "reliability engineer",
    notes: "",
  },
  {
    alias_id: "RA079",
    role_id: "CR019",
    alias: "Cyber Security Analyst",
    normalized_alias: "cyber security analyst",
    notes: "",
  },
  {
    alias_id: "RA080",
    role_id: "CR019",
    alias: "Information Security Analyst",
    normalized_alias: "information security analyst",
    notes: "",
  },
  {
    alias_id: "RA081",
    role_id: "CR019",
    alias: "Security Analyst",
    normalized_alias: "security analyst",
    notes: "",
  },
  {
    alias_id: "RA082",
    role_id: "CR019",
    alias: "Infosec Analyst",
    normalized_alias: "infosec analyst",
    notes: "",
  },
  {
    alias_id: "RA083",
    role_id: "CR020",
    alias: "Ethical Hacker",
    normalized_alias: "ethical hacker",
    notes: "",
  },
  {
    alias_id: "RA084",
    role_id: "CR020",
    alias: "Security Tester",
    normalized_alias: "security tester",
    notes: "",
  },
  {
    alias_id: "RA085",
    role_id: "CR020",
    alias: "Pentester",
    normalized_alias: "pentester",
    notes: "",
  },
  {
    alias_id: "RA086",
    role_id: "CR022",
    alias: "SOC Analyst",
    normalized_alias: "soc analyst",
    notes: "",
  },
  {
    alias_id: "RA087",
    role_id: "CR022",
    alias: "Security Operations Analyst",
    normalized_alias: "security operations analyst",
    notes: "",
  },
  {
    alias_id: "RA088",
    role_id: "CR023",
    alias: "Network Systems Engineer",
    normalized_alias: "network systems engineer",
    notes: "",
  },
  {
    alias_id: "RA089",
    role_id: "CR023",
    alias: "Network Infrastructure Engineer",
    normalized_alias: "network infrastructure engineer",
    notes: "",
  },
  {
    alias_id: "RA090",
    role_id: "CR024",
    alias: "Network Admin",
    normalized_alias: "network admin",
    notes: "",
  },
  {
    alias_id: "RA091",
    role_id: "CR024",
    alias: "Network Technician",
    normalized_alias: "network technician",
    notes: "",
  },
  {
    alias_id: "RA092",
    role_id: "CR025",
    alias: "Sysadmin",
    normalized_alias: "sysadmin",
    notes: "",
  },
  {
    alias_id: "RA093",
    role_id: "CR025",
    alias: "System Administrator",
    normalized_alias: "system administrator",
    notes: "",
  },
  {
    alias_id: "RA094",
    role_id: "CR025",
    alias: "Server Administrator",
    normalized_alias: "server administrator",
    notes: "",
  },
  {
    alias_id: "RA095",
    role_id: "CR026",
    alias: "IT Technician",
    normalized_alias: "it technician",
    notes: "",
  },
  {
    alias_id: "RA096",
    role_id: "CR026",
    alias: "IT Staff",
    normalized_alias: "it staff",
    notes: "Common PH job posting phrasing",
  },
  {
    alias_id: "RA097",
    role_id: "CR026",
    alias: "Technical Support",
    normalized_alias: "technical support",
    notes: "",
  },
  {
    alias_id: "RA098",
    role_id: "CR026",
    alias: "IT Specialist",
    normalized_alias: "it specialist",
    notes: "",
  },
  {
    alias_id: "RA099",
    role_id: "CR027",
    alias: "Tech Support Engineer",
    normalized_alias: "tech support engineer",
    notes: "",
  },
  {
    alias_id: "RA100",
    role_id: "CR027",
    alias: "Application Support Analyst",
    normalized_alias: "application support analyst",
    notes: "",
  },
  {
    alias_id: "RA101",
    role_id: "CR028",
    alias: "Help Desk Agent",
    normalized_alias: "help desk agent",
    notes: "",
  },
  {
    alias_id: "RA102",
    role_id: "CR028",
    alias: "Level 1 Support",
    normalized_alias: "level 1 support",
    notes: "",
  },
  {
    alias_id: "RA103",
    role_id: "CR029",
    alias: "UX Designer",
    normalized_alias: "ux designer",
    notes: "",
  },
  {
    alias_id: "RA104",
    role_id: "CR029",
    alias: "UI Designer",
    normalized_alias: "ui designer",
    notes: "",
  },
  {
    alias_id: "RA105",
    role_id: "CR029",
    alias: "Product Designer",
    normalized_alias: "product designer",
    notes: "Overlaps with CR030",
  },
  {
    alias_id: "RA106",
    role_id: "CR029",
    alias: "UX/UI Designer",
    normalized_alias: "ux/ui designer",
    notes: "",
  },
  {
    alias_id: "RA107",
    role_id: "CR029",
    alias: "Interaction Designer",
    normalized_alias: "interaction designer",
    notes: "",
  },
  {
    alias_id: "RA108",
    role_id: "CR030",
    alias: "Visual Designer",
    normalized_alias: "visual designer",
    notes: "",
  },
  {
    alias_id: "RA109",
    role_id: "CR031",
    alias: "User Researcher",
    normalized_alias: "user researcher",
    notes: "",
  },
  {
    alias_id: "RA110",
    role_id: "CR032",
    alias: "QA Tester",
    normalized_alias: "qa tester",
    notes: "",
  },
  {
    alias_id: "RA111",
    role_id: "CR032",
    alias: "Software Tester",
    normalized_alias: "software tester",
    notes: "",
  },
  {
    alias_id: "RA112",
    role_id: "CR032",
    alias: "Quality Assurance Specialist",
    normalized_alias: "quality assurance specialist",
    notes: "",
  },
  {
    alias_id: "RA113",
    role_id: "CR032",
    alias: "QA Analyst",
    normalized_alias: "qa analyst",
    notes: "",
  },
  {
    alias_id: "RA114",
    role_id: "CR033",
    alias: "Test Automation Engineer",
    normalized_alias: "test automation engineer",
    notes: "",
  },
  {
    alias_id: "RA115",
    role_id: "CR033",
    alias: "Automation QA Engineer",
    normalized_alias: "automation qa engineer",
    notes: "",
  },
  {
    alias_id: "RA116",
    role_id: "CR034",
    alias: "Project Manager",
    normalized_alias: "project manager",
    notes: "",
  },
  {
    alias_id: "RA117",
    role_id: "CR034",
    alias: "PM",
    normalized_alias: "pm",
    notes: "Ambiguous; also maps to Product Manager",
  },
  {
    alias_id: "RA118",
    role_id: "CR034",
    alias: "IT PM",
    normalized_alias: "it pm",
    notes: "",
  },
  {
    alias_id: "RA119",
    role_id: "CR035",
    alias: "Product Owner",
    normalized_alias: "product owner",
    notes: "",
  },
  {
    alias_id: "RA120",
    role_id: "CR035",
    alias: "PO",
    normalized_alias: "po",
    notes: "",
  },
  {
    alias_id: "RA121",
    role_id: "CR036",
    alias: "Agile Coach",
    normalized_alias: "agile coach",
    notes: "",
  },
  {
    alias_id: "RA122",
    role_id: "CR008",
    alias: "Junior Developer",
    normalized_alias: "junior developer",
    notes: "",
  },
  {
    alias_id: "RA123",
    role_id: "CR008",
    alias: "Junior Programmer",
    normalized_alias: "junior programmer",
    notes: "",
  },
  {
    alias_id: "RA124",
    role_id: "CR008",
    alias: "Entry Level Developer",
    normalized_alias: "entry level developer",
    notes: "",
  },
  {
    alias_id: "RA125",
    role_id: "CR008",
    alias: "Trainee Developer",
    normalized_alias: "trainee developer",
    notes: "",
  },
  {
    alias_id: "RA126",
    role_id: "CR008",
    alias: "Associate Software Engineer",
    normalized_alias: "associate software engineer",
    notes: "",
  },
];
